#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t cornellappdev/eatery:"$TRAVIS_COMMIT" --no-cache .
docker push cornellappdev/eatery:"$TRAVIS_COMMIT"
chmod 600 server.pem
ssh -i server.pem appdev@eatery-backend.cornellappdev.com "cd docker-compose; export IMAGE_TAG='$TRAVIS_COMMIT';
    docker stack deploy --compose-file docker-compose.yml the-stack"

